FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /mail ./cmd/mail/
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /mail-migrate ./cmd/mail-migrate/

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /mail /mail
COPY --from=builder /mail-migrate /mail-migrate
COPY migrations/mail /migrations/mail
EXPOSE 8890
ENTRYPOINT ["/mail"]
