apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "catalog.fullname" . }}
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "catalog.selectorLabels" . | nindent 6 }}
