apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mcp.fullname" . }}
  labels:
    {{- include "mcp.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "mcp.selectorLabels" . | nindent 6 }}
