apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: verify-db
  namespace: biqly
spec:
  refreshInterval: 1h
  secretStoreRef: { kind: ClusterSecretStore, name: vault-biqly }
  target:
    name: biqly-db-vault
    creationPolicy: Owner
  dataFrom:
    - extract: { key: db }
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: verify-security
  namespace: biqly
spec:
  refreshInterval: 1h
  secretStoreRef: { kind: ClusterSecretStore, name: vault-biqly }
  target:
    name: biqly-security-vault
    creationPolicy: Owner
  dataFrom:
    - extract: { key: security }
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: verify-auth
  namespace: biqly
spec:
  refreshInterval: 1h
  secretStoreRef: { kind: ClusterSecretStore, name: vault-biqly }
  target:
    name: biqly-auth-secrets-vault
    creationPolicy: Owner
  dataFrom:
    - extract: { key: auth }
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: verify-auth-db
  namespace: biqly
spec:
  refreshInterval: 1h
  secretStoreRef: { kind: ClusterSecretStore, name: vault-biqly }
  target:
    name: biqly-auth-db-vault
    creationPolicy: Owner
  dataFrom:
    - extract: { key: auth-db }
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: verify-ai
  namespace: biqly
spec:
  refreshInterval: 1h
  secretStoreRef: { kind: ClusterSecretStore, name: vault-biqly }
  target:
    name: biqly-ai-secrets-vault
    creationPolicy: Owner
  dataFrom:
    - extract: { key: ai }
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: verify-embedding
  namespace: biqly
spec:
  refreshInterval: 1h
  secretStoreRef: { kind: ClusterSecretStore, name: vault-biqly }
  target:
    name: biqly-embedding-secrets-vault
    creationPolicy: Owner
  dataFrom:
    - extract: { key: embedding }
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: verify-mail
  namespace: biqly
spec:
  refreshInterval: 1h
  secretStoreRef: { kind: ClusterSecretStore, name: vault-biqly }
  target:
    name: biqly-mail-secrets-vault
    creationPolicy: Owner
  dataFrom:
    - extract: { key: mail }
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: verify-mail-db
  namespace: biqly
spec:
  refreshInterval: 1h
  secretStoreRef: { kind: ClusterSecretStore, name: vault-biqly }
  target:
    name: biqly-mail-db-vault
    creationPolicy: Owner
  dataFrom:
    - extract: { key: mail-db }
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: verify-otel
  namespace: biqly
spec:
  refreshInterval: 1h
  secretStoreRef: { kind: ClusterSecretStore, name: vault-biqly }
  target:
    name: biqly-otel-secrets-vault
    creationPolicy: Owner
  dataFrom:
    - extract: { key: otel }
