apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-nginx
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  default.conf: |
{{ .Files.Get "config/default.conf" | indent 4 }}
