{{- if .Values.global.observability.alertmanager.enabled }}
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: biqly-alertmanager
  labels:
    {{- include "biqly.labels" . | nindent 4 }}
spec:
  route:
    receiver: webhook
    groupBy:
      - alertname
      - service
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h
  receivers:
    - name: webhook
      webhookConfigs:
        - urlSecret:
            name: {{ .Values.global.observability.alertmanager.webhookURLSecret.name }}
            key: {{ .Values.global.observability.alertmanager.webhookURLSecret.key }}
{{- end }}
