{{- if and .Values.global.networkPolicy.enabled .Values.global.networkPolicy.aiExternal.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: biqly-ai-egress-external
  labels:
    {{- include "biqly.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: ai
      app.kubernetes.io/part-of: biqly
  egress:
    {{- with .Values.global.networkPolicy.aiExternal.fqdnNames }}
    - toFQDNs:
        {{- range . }}
        - matchName: {{ . | quote }}
        {{- end }}
      toPorts:
        - ports:
            {{- range $.Values.global.networkPolicy.aiExternal.fqdnPorts }}
            - port: {{ . | quote }}
              protocol: TCP
            {{- end }}
    {{- end }}
    {{- with .Values.global.networkPolicy.aiExternal.cidrs }}
    - toCIDRSet:
        {{- range . }}
        - cidr: {{ . | quote }}
        {{- end }}
      toPorts:
        - ports:
            {{- range $.Values.global.networkPolicy.aiExternal.cidrPorts }}
            - port: {{ . | quote }}
              protocol: TCP
            {{- end }}
    {{- end }}
{{- end }}
