{{- if .Values.global.reflectedTLSSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.reflectedTLSSecret.name }}
  labels:
    {{- include "biqly.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.global.reflectedTLSSecret.annotations | nindent 4 }}
type: {{ .Values.global.reflectedTLSSecret.type }}
data:
  tls.crt: {{ required "global.reflectedTLSSecret.tlsCrt is required when reflectedTLSSecret.create=true" .Values.global.reflectedTLSSecret.tlsCrt | quote }}
  tls.key: {{ required "global.reflectedTLSSecret.tlsKey is required when reflectedTLSSecret.create=true" .Values.global.reflectedTLSSecret.tlsKey | quote }}
{{- end }}
