{{- if .Values.global.registrySecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.registrySecret.name }}
  labels:
    {{- include "biqly.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.global.registrySecret.annotations | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ required "global.registrySecret.dockerconfigjson is required when registrySecret.create=true" .Values.global.registrySecret.dockerconfigjson | quote }}
{{- end }}
