{{- if .Values.global.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "biqly.serviceAccountName" . }}
  labels:
    {{- include "biqly.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.global.serviceAccount.automountServiceAccountToken }}
{{- end }}
