apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: biqly
  namespace: argocd
spec:
  project: biqly
  source:
    repoURL: https://github.com/biqly/biqly.git
    targetRevision: main
    path: deploy/helm/biqly
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: biqly
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectHelmHooks=true
