apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: biqly
  namespace: argocd
spec:
  writeBackConfig:
    method: git:secret:argocd/argocd-image-updater-git
    gitConfig:
      branch: main
  commonUpdateSettings:
    updateStrategy: newest-build
    allowTags: regexp:^sha-[0-9a-f]{40}$
    ignoreTags:
      - latest
    forceUpdate: false
  applicationRefs:
    - namePattern: biqly
      images:
        - alias: ai
          imageName: ghcr.io/biqly/ai
          manifestTargets:
            helm:
              tag: ai.image.tag
        - alias: query
          imageName: ghcr.io/biqly/query
          manifestTargets:
            helm:
              tag: query.image.tag
        - alias: catalog
          imageName: ghcr.io/biqly/catalog
          manifestTargets:
            helm:
              tag: catalog.image.tag
        - alias: frontend
          imageName: ghcr.io/biqly/biqly-frontend
          manifestTargets:
            helm:
              tag: frontend.image.tag
        - alias: auth
          imageName: ghcr.io/biqly/biqly-auth
          manifestTargets:
            helm:
              tag: auth.image.tag
        - alias: auth-migrate
          imageName: ghcr.io/biqly/biqly-auth
          manifestTargets:
            helm:
              tag: auth.migrate.image.tag
        - alias: migrate
          imageName: ghcr.io/biqly/migrate
          manifestTargets:
            helm:
              tag: global.migrate.image.tag
