helm:
  parameters:
  - name: ai.image.tag
    value: sha-65a4c3506ed4d21f4540b4280e087af9460f53d6
    forcestring: true
  - name: catalog.image.tag
    value: sha-65a4c3506ed4d21f4540b4280e087af9460f53d6
    forcestring: true
  - name: frontend.image.tag
    value: sha-65a4c3506ed4d21f4540b4280e087af9460f53d6
    forcestring: true
  - name: global.migrate.image.tag
    value: sha-e3fda15049dd8cb2cf9bb0d40109edc2722b1463
    forcestring: true
  - name: image.name
    value: ghcr.io/biqly/migrate
    forcestring: true
  - name: query.image.tag
    value: sha-65a4c3506ed4d21f4540b4280e087af9460f53d6
    forcestring: true
