helm:
  parameters:
  - name: ai.image.tag
    value: sha-26639db3d6621f36029f3c33c2c9082a5f975839
    forcestring: true
  - name: catalog.image.tag
    value: sha-26639db3d6621f36029f3c33c2c9082a5f975839
    forcestring: true
  - name: frontend.image.tag
    value: sha-26639db3d6621f36029f3c33c2c9082a5f975839
    forcestring: true
  - name: global.migrate.image.tag
    value: sha-2ad3f2ed495f9c9e8e268d2e6defd33bc92c9b54
    forcestring: true
  - name: image.name
    value: ghcr.io/biqly/migrate
    forcestring: true
  - name: query.image.tag
    value: sha-26639db3d6621f36029f3c33c2c9082a5f975839
    forcestring: true
