apiVersion: v2
name: biqly
description: Biqly microservice umbrella chart
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: postgresql
    version: 18.6.7
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: catalog
    version: 0.1.0
    repository: file://charts/catalog
  - name: query
    version: 0.1.0
    repository: file://charts/query
  - name: ai
    version: 0.1.0
    repository: file://charts/ai
