global:
  config:
    BI_LOG_LEVEL: info
    BI_LOG_FORMAT: json

catalog:
  replicaCount: 2

query:
  replicaCount: 2
  autoscaling:
    minReplicas: 2
    maxReplicas: 6

ai:
  replicaCount: 2
  autoscaling:
    minReplicas: 2
    maxReplicas: 4
