global:
  imagePullSecrets:
    - name: ghcr-registry
  secrets:
    createSecrets: false
  config:
    BI_LOG_LEVEL: info
    BI_LOG_FORMAT: json
  observability:
    serviceMonitor:
      enabled: false
    prometheusRules:
      enabled: false
    alertmanager:
      enabled: false
    logs:
      vectorConfig:
        enabled: false
    tracing:
      otelCollector:
        enabled: false
      jaeger:
        enabled: false
    dashboards:
      enabled: true

catalog:
  replicaCount: 2
  autoscaling:
    minReplicas: 2
    maxReplicas: 4

query:
  replicaCount: 2
  autoscaling:
    minReplicas: 2
    maxReplicas: 6

ai:
  replicaCount: 2
  rollout:
    enabled: false
  autoscaling:
    minReplicas: 2
    maxReplicas: 4
