package ai

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"github.com/bytedance/sonic"
	"log/slog"
	"regexp"
	"strings"
	"unicode/utf8"

	"github.com/biqly/biqly/internal/ai/jsonextract"
	providerpkg "github.com/biqly/biqly/internal/ai/provider"
	"github.com/biqly/biqly/internal/core"
	"github.com/biqly/biqly/internal/datasource"
	"github.com/biqly/biqly/internal/metadata"
	"github.com/biqly/biqly/internal/security"
)

// identRegex matches catalog names we interpolate into a sample query after
// dialect-specific quoting. Leading digits and internal dots are allowed (e.g. "2012",
// "Emp.StartDate"); spaces, semicolons, and quotes are rejected.
var identRegex = regexp.MustCompile(`^[A-Za-z0-9_.$]+$`)

func validIdent(s string) bool { return identRegex.MatchString(s) }

// DescribeService generates table/column descriptions from sampled rows using an LLM.
type DescribeService struct {
	client               providerpkg.Provider
	model                string
	metaRepo             *metadata.Repository
	driverReg            *datasource.Registry
	poolCache            *datasource.PoolCache
	translator           *TranslationService
	encryptor            *security.Encryption
	sampleRows           int
	maxCellRunes         int
	maxSampleRowsHardCap int
}

// NewDescribeService wires the dependencies needed to sample, prompt, and persist descriptions.
func NewDescribeService(client providerpkg.Provider, metaRepo *metadata.Repository, driverReg *datasource.Registry, translator *TranslationService, sampleRows, maxCellRunes, maxSampleRowsHardCap int, encryptor *security.Encryption) *DescribeService {
	if sampleRows <= 0 {
		sampleRows = 10
	}
	if maxCellRunes <= 0 {
		maxCellRunes = 500
	}
	if maxSampleRowsHardCap <= 0 {
		maxSampleRowsHardCap = 12
	}
	return &DescribeService{
		client:               client,
		metaRepo:             metaRepo,
		driverReg:            driverReg,
		translator:           translator,
		encryptor:            encryptor,
		sampleRows:           sampleRows,
		maxCellRunes:         maxCellRunes,
		maxSampleRowsHardCap: maxSampleRowsHardCap,
	}
}

// WithModel labels the describe service with the model name that callers will
// see in DescribeResult.Model. Pass the same string configured via BI_AI_MODEL
// so the UI can display "Bu açıklama X modeli ile üretildi". Returning the
// service keeps the wire-up call chain compact.
func (s *DescribeService) WithModel(model string) *DescribeService {
	s.model = model
	return s
}

func (s *DescribeService) WithPoolCache(p *datasource.PoolCache) *DescribeService {
	s.poolCache = p
	return s
}

// DescribeRequest captures the inputs for a single-table description run.
type DescribeRequest struct {
	DatasourceID string `json:"datasource_id"`
	Schema       string `json:"schema"`
	Table        string `json:"table"`
	SampleSize   int    `json:"sample_size,omitempty"`
	AutoApply    bool   `json:"auto_apply,omitempty"`
}

// DescribeResult is what the AI proposed (and optionally what was persisted).
type DescribeResult struct {
	Table       string              `json:"table"`
	Schema      string              `json:"schema"`
	Description string              `json:"description"`
	Columns     []ColumnDescription `json:"columns"`
	Applied     bool                `json:"applied"`
	SampleRows  int                 `json:"sample_rows"`
	// Model identifies the LLM that produced this description so the UI can
	// surface "generated by X". Empty when the service wasn't labelled via
	// WithModel — older deployments simply omit the badge.
	Model              string `json:"model,omitempty"`
	TranslationApplied bool   `json:"translation_applied,omitempty"`
	TranslationModel   string `json:"translation_model,omitempty"`
	TranslationError   string `json:"translation_error,omitempty"`

	// originalDescription / originalColumns capture the English LLM output BEFORE
	// the translator post-processes it. They become the raw metadata description
	// and English overlay; translated values are stored under the target locale.
	originalDescription string
	originalColumns     []ColumnDescription
	originalLang        string
}

// ColumnDescription is one column's AI-generated description.
type ColumnDescription struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

// Describe fetches a sample, asks the LLM, parses suggestions, and (optionally) saves them.
func (s *DescribeService) Describe(ctx context.Context, req DescribeRequest) (*DescribeResult, error) {
	if req.DatasourceID == "" || req.Table == "" {
		return nil, errors.New("datasource_id and table are required")
	}

	limit := req.SampleSize
	if limit <= 0 {
		limit = s.sampleRows
	}
	if limit > s.maxSampleRowsHardCap {
		limit = s.maxSampleRowsHardCap
	}

	ds, err := s.metaRepo.GetDatasource(ctx, req.DatasourceID)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", core.ErrLoadDatasource, err)
	}

	driver, err := s.driverReg.Get(ds.Type)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", core.ErrLoadDriver, err)
	}

	cols, err := s.metaRepo.ListColumns(ctx, ds.ID, req.Schema, req.Table)
	if err != nil {
		return nil, fmt.Errorf("list columns: %w", err)
	}
	if len(cols) == 0 {
		return nil, fmt.Errorf("no columns found for %s.%s — run sync-metadata first", req.Schema, req.Table)
	}
	// Very wide tables: fewer rows keep the LLM prompt bounded.
	if len(cols) > 80 && limit > 4 {
		limit = 4
	} else if len(cols) > 40 && limit > 6 {
		limit = 6
	}

	dsn, err := metadata.RuntimeDSN(ds, s.encryptor)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", core.ErrLoadDatasource, err)
	}
	var db *sql.DB
	if s.poolCache != nil {
		db, err = s.poolCache.Get(ctx, driver, ds.ID, dsn)
	} else {
		db, err = driver.Open(ctx, dsn)
		if err == nil {
			defer func() { _ = db.Close() }()
		}
	}
	if err != nil {
		return nil, fmt.Errorf("%w: %w", core.ErrConnection, err)
	}

	sample, err := FetchTableSample(ctx, db, driver.Dialect(), cols, req.Schema, req.Table, limit, s.maxCellRunes)
	if err != nil {
		return nil, fmt.Errorf("fetch sample: %w", err)
	}

	prompt := buildDescribePrompt(req.Schema, req.Table, cols, sample)
	gen, err := s.client.Generate(ctx, prompt)
	if err != nil {
		return nil, fmt.Errorf("ai generate: %w", err)
	}

	tableDesc, colDescs, err := parseDescribeResponse(gen.Content)
	if err != nil {
		return nil, fmt.Errorf("parse ai response: %w", err)
	}

	result := &DescribeResult{
		Schema:      req.Schema,
		Table:       req.Table,
		Model:       s.model,
		Description: tableDesc,
		Columns:     colDescs,
		SampleRows:  len(sample),
	}
	s.translateDescribeResult(ctx, result)

	if req.AutoApply {
		if err := s.apply(ctx, cols, result); err != nil {
			return result, fmt.Errorf("apply descriptions: %w", err)
		}
		result.Applied = true
	}

	return result, nil
}

func (s *DescribeService) translateDescribeResult(ctx context.Context, result *DescribeResult) {
	if s.translator == nil {
		return
	}
	// Snapshot the LLM's English output before the translator overwrites
	// result.Description/Columns in place.
	result.originalDescription = result.Description
	result.originalColumns = append([]ColumnDescription(nil), result.Columns...)
	result.originalLang = "en"
	if err := s.translator.TranslateDescribeResult(ctx, result); err != nil {
		result.TranslationModel = s.translator.Model()
		result.TranslationError = err.Error()
		// Clear snapshot so apply() does not store a stale English overlay.
		result.originalDescription = ""
		result.originalColumns = nil
		slog.WarnContext(ctx, "metadata description translation failed", "error", err)
	}
}

func shrinkSampleForPrompt(rows []map[string]any, maxCellRunes int) []map[string]any {
	if maxCellRunes <= 0 {
		maxCellRunes = 500
	}
	anyTruncated := false
	for _, row := range rows {
		for _, v := range row {
			if needsTruncation(v, maxCellRunes) {
				anyTruncated = true
				break
			}
		}
		if anyTruncated {
			break
		}
	}
	if !anyTruncated {
		return rows
	}

	out := make([]map[string]any, len(rows))
	for i, row := range rows {
		m := make(map[string]any, len(row))
		for k, v := range row {
			m[k] = truncateAnyForPrompt(v, maxCellRunes)
		}
		out[i] = m
	}
	return out
}

func needsTruncation(v any, maxRunes int) bool {
	if v == nil {
		return false
	}
	switch x := v.(type) {
	case []byte:
		return utf8.RuneCount(x) > maxRunes
	case string:
		return utf8.RuneCountInString(x) > maxRunes
	case int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64, float32, float64, bool:
		return false
	default:
		return utf8.RuneCountInString(fmt.Sprint(x)) > maxRunes
	}
}

func truncateAnyForPrompt(v any, maxRunes int) any {
	if v == nil {
		return nil
	}
	switch x := v.(type) {
	case []byte:
		return truncateStringRunes(string(x), maxRunes)
	case string:
		return truncateStringRunes(x, maxRunes)
	case int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64, float32, float64, bool:
		return v
	default:
		s := fmt.Sprint(x)
		if utf8.RuneCountInString(s) <= maxRunes {
			return v
		}
		return truncateStringRunes(s, maxRunes)
	}
}

func truncateStringRunes(s string, maxRunes int) string {
	if maxRunes <= 0 {
		return ""
	}
	if utf8.RuneCountInString(s) <= maxRunes {
		return s
	}
	runes := []rune(s)
	return string(runes[:maxRunes]) + "…"
}

//nolint:gocognit
func (s *DescribeService) apply(ctx context.Context, cols []metadata.Column, result *DescribeResult) error {
	colByName := make(map[string]metadata.Column, len(cols))
	for i := range cols {
		colByName[cols[i].ColumnName] = cols[i]
	}

	tableDescription := result.Description
	columnDescriptions := result.Columns
	if result.TranslationApplied && result.originalDescription != "" {
		tableDescription = result.originalDescription
		columnDescriptions = result.originalColumns
	}

	if tableDescription != "" && len(cols) > 0 { // Apply to the first matching table_id (all sampled cols share the same table).
		if err := s.metaRepo.UpdateTableDescription(ctx, cols[0].TableID, new(tableDescription)); err != nil {
			return fmt.Errorf("update table description: %w", err)
		}
	}

	for _, cd := range columnDescriptions {
		if cd.Description == "" {
			continue
		}
		col, ok := colByName[cd.Name]
		if !ok {
			continue
		}
		if err := s.metaRepo.UpdateColumnDescription(ctx, col.ID, new(cd.Description)); err != nil {
			return fmt.Errorf("update column %s: %w", cd.Name, err)
		}
	}

	if result.originalLang != "" && result.TranslationApplied && len(cols) > 0 { //nolint:nestif
		if result.originalDescription != "" {
			if err := s.metaRepo.UpsertTranslation(ctx, metadata.Translation{
				EntityType: metadata.EntityTypeTable,
				EntityID:   cols[0].TableID,
				Lang:       result.originalLang,
				Field:      metadata.TranslationFieldDescription,
				Value:      result.originalDescription,
			}); err != nil {
				slog.Warn("upsert original table translation", "table_id", cols[0].TableID, "lang", result.originalLang, "err", err)
			}
		}
		for _, cd := range result.originalColumns {
			if cd.Description == "" {
				continue
			}
			col, ok := colByName[cd.Name]
			if !ok {
				continue
			}
			if err := s.metaRepo.UpsertTranslation(ctx, metadata.Translation{
				EntityType: metadata.EntityTypeColumn,
				EntityID:   col.ID,
				Lang:       result.originalLang,
				Field:      metadata.TranslationFieldDescription,
				Value:      cd.Description,
			}); err != nil {
				slog.Warn("upsert original column translation", "column_id", col.ID, "lang", result.originalLang, "err", err)
			}
		}

		targetLang := s.translator.TargetCode()
		if targetLang != "" {
			if result.Description != "" {
				if err := s.metaRepo.UpsertTranslation(ctx, metadata.Translation{
					EntityType: metadata.EntityTypeTable,
					EntityID:   cols[0].TableID,
					Lang:       targetLang,
					Field:      metadata.TranslationFieldDescription,
					Value:      result.Description,
				}); err != nil {
					slog.Warn("upsert translated table description", "table_id", cols[0].TableID, "lang", targetLang, "err", err)
				}
			}
			for _, cd := range result.Columns {
				if cd.Description == "" {
					continue
				}
				col, ok := colByName[cd.Name]
				if !ok {
					continue
				}
				if err := s.metaRepo.UpsertTranslation(ctx, metadata.Translation{
					EntityType: metadata.EntityTypeColumn,
					EntityID:   col.ID,
					Lang:       targetLang,
					Field:      metadata.TranslationFieldDescription,
					Value:      cd.Description,
				}); err != nil {
					slog.Warn("upsert translated column description", "column_id", col.ID, "lang", targetLang, "err", err)
				}
			}
		}
	}
	return nil
}

func buildDescribePrompt(schema, table string, cols []metadata.Column, sample []map[string]any) string {
	var sb strings.Builder
	sb.WriteString("You are a data documentation assistant. Examine the table schema and sample rows, then write concise, business-friendly descriptions.\n\n")
	sb.WriteString("## Rules\n")
	sb.WriteString("- Output ONLY valid JSON matching the schema below. No markdown, no explanation.\n")
	sb.WriteString("- Use strict JSON: every property name MUST be double-quoted (e.g. \"table_description\", not table_description:).\n")
	sb.WriteString("- Keep descriptions under 200 characters each.\n")
	sb.WriteString("- Describe the business meaning, not the data type.\n")
	sb.WriteString("- Write descriptions in English. A separate translation layer handles Turkish output.\n")
	sb.WriteString("- Keep original table/column names and common technical terms when useful, so descriptions still bridge to the physical schema.\n")
	sb.WriteString("- If you cannot infer a column from the sample, leave its description empty.\n\n")

	_, _ = fmt.Fprintf(&sb, "## Table: %s.%s\n", schema, table)
	sb.WriteString("### Columns\n")
	for i := range cols {
		c := &cols[i]
		line := fmt.Sprintf("- %s (%s", c.ColumnName, c.DataType)
		if c.IsPrimaryKey {
			line += ", primary key"
		}
		if c.IsForeignKey && c.ReferencedTable != nil {
			line += fmt.Sprintf(", FK -> %s.%s", *c.ReferencedTable, derefStr(c.ReferencedColumn))
		}
		line += ")"
		if c.Description != nil && *c.Description != "" {
			line += fmt.Sprintf(" — current: %q", *c.Description)
		}
		sb.WriteString(line)
		sb.WriteString("\n")
	}

	sb.WriteString("\n### Sample Rows (JSON, compact; cell strings may be truncated)\n")
	if data, err := sonic.ConfigStd.Marshal(sample); err == nil {
		_, _ = sb.Write(data)
		sb.WriteString("\n")
	}

	sb.WriteString("\n## Output Schema\n")
	sb.WriteString(`{"table_description": "...", "columns": [{"name": "col_name", "description": "..."}]}`)

	return sb.String()
}

func parseDescribeResponse(raw string) (string, []ColumnDescription, error) {
	cleaned := jsonextract.TrimToJSONObject(raw)

	var payload struct {
		TableDescription string              `json:"table_description"`
		Columns          []ColumnDescription `json:"columns"`
	}
	if err := sonic.ConfigStd.Unmarshal([]byte(cleaned), &payload); err != nil {
		return "", nil, fmt.Errorf("invalid JSON from AI: %w", err)
	}
	return payload.TableDescription, payload.Columns, nil
}

func derefStr(s *string) string {
	if s == nil {
		return ""
	}
	return *s
}
