{{- if .Values.global.secrets.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secretNames.authSecret }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
type: Opaque
stringData:
  BI_AUTH_ENCRYPTION_KEY: {{ required "global.secrets.BI_AUTH_ENCRYPTION_KEY is required" .Values.global.secrets.BI_AUTH_ENCRYPTION_KEY | quote }}
  BI_AUTH_INTERNAL_TOKEN: {{ required "global.secrets.BI_AUTH_INTERNAL_TOKEN is required" .Values.global.secrets.BI_AUTH_INTERNAL_TOKEN | quote }}
  BI_AUTH_JWT_PRIVATE_KEY: {{ required "global.secrets.BI_AUTH_JWT_PRIVATE_KEY is required" .Values.global.secrets.BI_AUTH_JWT_PRIVATE_KEY | quote }}
  {{- with .Values.global.secrets.BI_AUTH_GITHUB_CLIENT_SECRET }}
  BI_AUTH_GITHUB_CLIENT_SECRET: {{ . | quote }}
  {{- end }}
  {{- with .Values.global.secrets.BI_AUTH_GOOGLE_CLIENT_SECRET }}
  BI_AUTH_GOOGLE_CLIENT_SECRET: {{ . | quote }}
  {{- end }}
  {{- with .Values.global.secrets.BI_AUTH_SMTP_USER }}
  BI_AUTH_SMTP_USER: {{ . | quote }}
  {{- end }}
  {{- with .Values.global.secrets.BI_AUTH_SMTP_PASS }}
  BI_AUTH_SMTP_PASS: {{ . | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secretNames.authDB }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
type: Opaque
stringData:
  BI_AUTH_DB_DSN: {{ required "global.secrets.BI_AUTH_DB_DSN is required" .Values.global.secrets.BI_AUTH_DB_DSN | quote }}
{{- end }}
