apiVersion: v1
kind: Secret
metadata:
  name: {{ include "query.fullname" . }}-secret
  labels:
    {{- include "query.labels" . | nindent 4 }}
type: Opaque
stringData:
  BI_METADATA_DB_DSN: {{ required "global.secrets.BI_METADATA_DB_DSN is required" .Values.global.secrets.BI_METADATA_DB_DSN | quote }}
  BI_ENCRYPTION_KEY: {{ required "global.secrets.BI_ENCRYPTION_KEY is required" .Values.global.secrets.BI_ENCRYPTION_KEY | quote }}
  {{- with .Values.global.secrets.BI_INTERNAL_API_TOKEN }}
  BI_INTERNAL_API_TOKEN: {{ . | quote }}
  {{- end }}
