global:
  biqlyImageRegistry: ghcr.io/biqly
  imagePullSecrets: []
  registrySecret:
    create: false
    name: ghcr-registry
  serviceAccount:
    name: biqly
    automountServiceAccountToken: false

replicaCount: 1
image:
  repository: frontend
  tag: latest
  pullPolicy: IfNotPresent
service:
  port: 8080
resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
route:
  enabled: true
  pathPrefixes:
    - /

